# Generated by Django 3.0.3 on 2020-07-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dna_app', '0003_remove_sequencemodel_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencemodel',
            name='result',
            field=models.TextField(default='<Working on it!>'),
        ),
        migrations.AlterField(
            model_name='sequencemodel',
            name='seq',
            field=models.TextField(default='--'),
            preserve_default=False,
        ),
    ]
