# Generated by Django 3.0.3 on 2020-07-01 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dna_app', '0004_auto_20200701_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencemodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
